name: editor_config
description: A parser for EditorConfig file.
version: 0.1.0
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/editor_config

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  glob: '>=1.0.0 <1.1.0'
  ini: '>=1.1.0 <1.2.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
