name: editor_config
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  glob: '>=1.0.0 <1.1.0'
  ini: '>=1.1.0 <1.2.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
